/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Conversation {
  'id' : bigint,
  'title' : string,
  'messages' : Array<Message>,
  'createdAt' : bigint,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
}
export interface UserProfile {
  'username' : string,
  'displayName' : string,
  'createdDate' : bigint,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createConversation' : ActorMethod<[string], Conversation>,
  'getAllConversations' : ActorMethod<
    [],
    Array<[Principal, Array<Conversation>]>
  >,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[bigint], Conversation>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getMessages' : ActorMethod<[bigint], Array<Message>>,
  'getProfile' : ActorMethod<[string], UserProfile>,
  'getUserConversation' : ActorMethod<[Principal, bigint], Conversation>,
  'getUserConversations' : ActorMethod<[Principal], Array<Conversation>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, string, string], Message>,
  'signUp' : ActorMethod<[string, string, string, string], boolean>,
  'systemDescription' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];