/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'createdAt' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdDate' : IDL.Int,
  'email' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'callDeepSeek' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createConversation' : IDL.Func([IDL.Text], [Conversation], []),
  'createGuestConversation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [Conversation],
      [],
    ),
  'getAllConversations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Conversation)))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Nat], [Conversation], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getGuestConversations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Conversation)],
      ['query'],
    ),
  'getGuestMessages' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getProfile' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'getUserConversation' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [Conversation],
      ['query'],
    ),
  'getUserConversations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Conversation)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendGuestMessage' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [Message],
      [],
    ),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Message], []),
  'signUp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'systemDescription' : IDL.Func([], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'createdAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdDate' : IDL.Int,
    'email' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'callDeepSeek' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createConversation' : IDL.Func([IDL.Text], [Conversation], []),
    'createGuestConversation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [Conversation],
        [],
      ),
    'getAllConversations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Conversation)))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func([IDL.Nat], [Conversation], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getGuestConversations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Conversation)],
        ['query'],
      ),
    'getGuestMessages' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getProfile' : IDL.Func([IDL.Text], [UserProfile], ['query']),
    'getUserConversation' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [Conversation],
        ['query'],
      ),
    'getUserConversations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Conversation)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendGuestMessage' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [Message],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Message], []),
    'signUp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'systemDescription' : IDL.Func([], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };